### ISSUE TITLE
cy.msalLogin is not a function

### ISSUE THREAD

**Issue by soajetunmobi** [joelmeiller/cypress-msal-login#4]
I was getting the aforementioned error and I added import 'cypress-msal-login' to cypress/support/index.js. After adding that I then got this error: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'. Please kindly help me out.

**Comment by ivantrave** [comment]
Same here. Is there any missing configuration in the documentation? thanks

**Comment by ivantrave** [comment]
Tried adding `import 'cypress-msal-login'` to `cypress/support/index.js` file and it gives now a different error:
```
Command:  wrap
cypress_runner.js:194914 Error:    TypeError: Cannot read properties of null (reading 'get')
```

Probably related to this?
```
cy.wrap(null).then(function () { return __awaiter(_this, void 0, void 0, function () {
            return __generator(this, function (_a) {
...
```

Not sure exactly what `cy.wrap(null)` is used for

**Comment by andreaslarssen** [comment]
Same. Can not use this

**Comment by joelmeiller** [comment]
@andreaslarssen @soajetunmobi @ivantrave I updated the library to version 1.1.0 and removed the cy.warp(null). It's tested with latest Cypress version 12.8.1.
Please let me know if you still face the issue.
